#! /bin/sh
#


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# xfce-polkit
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# bspwm window sizing
bspc config border_width 2
bspc config window_gap 12
bspc config split_ratio 0.50

bspc config focused_border_color '#f38ba8'
bspc config normal_border_color '#f5c2e7'
bspc config active_border_color '#f5c2e7' 
# bspc config presel_feedback_color #f5c2e7

# hold alt key to resize/move windows
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

# focus follows cursor placement
bspc config focus_follows_pointer true


# double monitor setup
xrandr --output HDMI1 --right-of eDP1 &

# key mappings
xmodmap .Xmodmap &

# fix cursor  
xsetroot -cursor_name left_ptr

sxhkd -c ~/.config/sxhkd/sxhkdrc &

# for protonvpn to work
gnome-keyring-daemon --start
nm-applet &

# language input
fcitx5 -d
