#! /bin/sh
#


pgrep -x sxhkd > /dev/null || sxhkd &

default_workspaces() {
	for monitor in `xrandr -q | grep -w 'connected' | cut -d' ' -f1`; do
		bspc monitor "$monitor" -d  '一' '二' '三' '四' '五' '六' '七' '八' 
	done
}

## Two Monitors Setup (Laptop and external monitor, set 4 workspaces on each monitor)
two_monitors_workspaces() {
	# change these values according to your system
	# you can use `xrandr -q` to get the names of monitors
	INTERNAL_MONITOR="eDP1"
	EXTERNAL_MONITOR="HDMI1"
	if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
		bspc monitor "$EXTERNAL_MONITOR" -d '五' '六' '七' '八'
		bspc monitor "$INTERNAL_MONITOR" -d '一' '二' '三' '四'
		bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
	else
		bspc monitor "$INTERNAL_MONITOR" -d '一' '二' '三' '四' '五' '六' '七' '八' 	
	fi
}

two_monitors_workspaces

declare -a floating=(Thunar SimpleScreenRecorder qpaeq PulseEffects)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

bspc config border_width         2
bspc config window_gap           15

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# xfce-polkit
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# bspwm window sizing
bspc config border_width 2
bspc config window_gap 12
bspc config split_ratio 0.50

bspc config focused_border_color '#f38ba8'
bspc config normal_border_color '#f5c2e7'
bspc config active_border_color '#f5c2e7' 
# bspc config presel_feedback_color #f5c2e7

# hold alt key to resize/move windows
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

# focus follows cursor placement
bspc config focus_follows_pointer true

# picom
picom &

# double monitor setup
xrandr --output HDMI1 --right-of eDP1 &

# fix cursor  
xsetroot -cursor_name left_ptr

sxhkd -c ~/.config/sxhkd/sxhkdrc &

# for protonvpn to work
gnome-keyring-daemon --start
nm-applet &

# language input
fcitx5 -d

# mpd
mpd &

# notificaton daemon
dunst &

xmodmap ~/.Xmodmap

# launch polybar
(
  flock 200

  while pgrep -u $UID -x polybar > /dev/null; do sleep 0.5; done

  outputs=$(xrandr --query | grep " connected" | cut -d" " -f1)
  tray_output=eDP1

  for m in $outputs; do
    if [[ $m == "HDMI1" ]]; then
        tray_output=$m
    fi
  done

  for m in $outputs; do
    export MONITOR=$m
    export TRAY_POSITION=none
    if [[ $m == $tray_output ]]; then
      TRAY_POSITION=right
    fi

    polybar --reload example </dev/null >/var/tmp/polybar-$m.log 2>&1 200>&- &
    disown
  done
) 200>/var/tmp/polybar-launch.lock

# xfce-4 powermanager
xfce4-power-manager &

# set wallpaper 
feh --bg-scale ~/wp/ARCH.jpg
